title: "JORGE'S BLOG"
author: "Jorge Espinoza Abud"
description: "Just sharing ideas and releasing some stress in written form"
permalink: /:title/
lang: "en"

show_footer: true           # show the "previous" and "next" links at the end of each post
dark_theme: true            # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - Home: "https://jabud.github.io/"
  - About: "/about"
  - Contact: "/contact"

# icons:                      # icons in the header, see http://fontawesome.com/icons
 # envelope: "mailto:jorge@jabud.tech"
 # github: "https://github.com/jabud"
 # linkedin: "https://www.linkedin.com/in/jorgeabud/"
 # rss: "/blog/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout

theme: jekyll-theme-minimal
